#play lavel variables
- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}

#variables form a file
- name: play variable form a file
  hosts: localhost
# var_files only works on play level , on the tasks you cannot load the files
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from a file
      ansible.builtin.debug:
        msg: URL =  {{ URL }}

# Task level variable
- name: play variable
  hosts: localhost
  tasks:
    - name: print task level variable
      vars:  # these vars are only for this task ,next tasks on same play cannot access
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

#inventory level variables
- name: variable from inventory
  hosts: all
  tasks:
    - name: print play variable from inventory
      ansible.builtin.debug:
        msg: "URL ={{ URL }}, Hostname of Server = {{ ansible_hostname }}"

- name: Register a variable
  hosts: localhost
  tasks:
    - name: Gte uptime output
      ansible.builtin.shell: uptime
      register: out

    - name: Print out
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Declare a variable
      ansible.builtin.set_fact:   # for feature use need a variable set_fact
        status: "{{ out.rc }}"

    - name: print status
      ansible.builtin.debug:
        msg: "{{ status }}"